chore: update obsolete function
skymavis/mavis-id-unity pull request #28
Opened 2024-11-12 10:14 UTC by thienNH0

2024-11-12 10:20 UTC, long-duc-nguyen-skymavis requested changes
+ SHOULD: Wrap deprecated API in `#region Deprecated`.
+ MUST: Add 1 separator line for each obsolete method.

2024-11-13 04:50 UTC, long-duc-nguyen-skymavis requested changes
MUST: Use `SkyMavis.Waypoint` instead of `SkyMavis.Waypoint.Waypoint`.

2024-11-13 04:50 UTC, long-duc-nguyen-skymavis commented on Runtime/Waypoint.cs
> +        public static void Init(string waypointOrigin, string clientId, string deeplinkSchema, string rpcUrl, int chainId)
MUST: Need `Obsolete` attribute as well.

2024-11-13 04:50 UTC, long-duc-nguyen-skymavis commented on Runtime/Waypoint.cs
> +        #region Deprecated Code
SHOULD: Call it `Deprecated API`.

2024-11-13 04:50 UTC, long-duc-nguyen-skymavis commented on Runtime/Waypoint.cs
> +        [Obsolete("To be removed in 0.5.0. Use SkyMavis.Waypoint.Waypoint.SendTransaction instead.")]
MUST: `SendTransaction()` with parentheses `().

2024-11-13 06:18 UTC, thienNH0 commented on Runtime/Waypoint.cs
> +        public static void Init(string waypointOrigin, string clientId, string deeplinkSchema, string rpcUrl, int chainId)
Done !

2024-11-13 06:18 UTC, thienNH0 commented on Runtime/Waypoint.cs
> +        #region Deprecated Code
Done !

2024-11-13 06:18 UTC, thienNH0 commented on Runtime/Waypoint.cs
> +        [Obsolete("To be removed in 0.5.0. Use SkyMavis.Waypoint.Waypoint.SendTransaction instead.")]
Done !

2024-11-13 06:41 UTC, long-duc-nguyen-skymavis approved these changes

2024-11-13 06:42 UTC, merged